name: Publish output MD to github pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run daily arxiv"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write  # Critical for deploy-pages action

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Latest Artifact ID and Download
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        # Debug: Print GitHub CLI version and authentication
        gh --version
        
        # Fetch workflows and debug
        echo "Fetching workflows..."
        WORKFLOWS=$(gh api -H "Accept: application/vnd.github+json" \
          /repos/dev-excap/arxiv-bot/actions/workflows)
        echo "$WORKFLOWS" | jq .
        
        # Find workflow ID
        WORKFLOW_ID=$(echo "$WORKFLOWS" | jq '.workflows[] | select(.name == "Run daily arxiv") | .id')
        echo "Workflow ID: $WORKFLOW_ID"
        
        # Fetch workflow runs
        echo "Fetching workflow runs..."
        WORKFLOW_RUNS=$(gh api -H "Accept: application/vnd.github+json" \
          "/repos/dev-excap/arxiv-bot/actions/workflows/${WORKFLOW_ID}/runs")
        echo "$WORKFLOW_RUNS" | jq .
        
        # Get the latest run ID
        RUN_ID=$(echo "$WORKFLOW_RUNS" | jq '.workflow_runs[0].id')
        echo "Latest Run ID: $RUN_ID"
        
        # Fetch artifacts for this run
        echo "Fetching artifacts for run $RUN_ID..."
        ARTIFACTS=$(gh api -H "Accept: application/vnd.github+json" \
          "/repos/dev-excap/arxiv-bot/actions/runs/${RUN_ID}/artifacts")
        echo "$ARTIFACTS" | jq .
        
        # Get the artifact ID
        ARTIFACT_ID=$(echo "$ARTIFACTS" | jq '.artifacts[0].id')
        echo "Artifact ID: $ARTIFACT_ID"
        
        # Download the artifact
        echo "Downloading artifact $ARTIFACT_ID..."
        gh api -H "Accept: application/vnd.github+json" \
          "/repos/dev-excap/arxiv-bot/actions/artifacts/${ARTIFACT_ID}/zip" \
          > artifact.zip
        
        # Unzip and list contents
        unzip artifact.zip
        ls -la

    - name: Check for output.md
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: output.md

    - name: Convert output.md to pages
      uses: wranders/markdown-to-pages-action@v0.1
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: output.md

    - uses: actions/upload-pages-artifact@v3
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        path: dist

    - uses: actions/deploy-pages@v4
      if: steps.check_files.outputs.files_exists == 'true'
      id: deployment
