name: Publish output MD to github pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run daily arxiv"]
    types:
      - completed
permissions: write-all


jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      file-exists: ${{ steps.file-check.outputs.file_exists }}
    steps:
    - uses: actions/checkout@v4
    - name: Debug Workflow Run Information
      run: |
        echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
    - name: List Recent Artifacts
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh api -H "Accept: application/vnd.github+json" \
          /repos/dev-excap/arxiv-bot/actions/artifacts \
          | jq '.artifacts[0]'
    
    - name: Download Specific Artifact
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        ARTIFACT_ID=$(gh api -H "Accept: application/vnd.github+json" \
          /repos/dev-excap/arxiv-bot/actions/artifacts \
          | jq '.artifacts[0].id')
        
        gh api -H "Accept: application/vnd.github+json" \
          /repos/dev-excap/arxiv-bot/actions/artifacts/${ARTIFACT_ID}/zip \
          > artifact.zip
        
        unzip artifact.zip
    - uses: actions/download-artifact@v4
      with:
        name: arxiv-scanner-outputs
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo

    # ✅ Display downloaded files
    - name: Display structure of downloaded files
      run: ls -R
    - name: Check for output.md
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: output.md
    - name: Convert output.md to pages
      uses: wranders/markdown-to-pages-action@v0.1
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: output.md
    - uses: actions/upload-pages-artifact@v3
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        path: dist
    - uses: actions/deploy-pages@v4
      if: steps.check_files.outputs.files_exists == 'true'
      id: deployment
